[tool.poetry]
name = "task-1"
version = "0.1.0"
description = ""
authors = ["PM"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
serverless-psycopg2 = "^0.0.2"
jsonschema = "^4.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
